function javascript(){var bb='',$=' top: -1000px;',xb='" for "gwt:onLoadErrorFn"',vb='" for "gwt:onPropertyErrorFn"',hb='");',yb='#',Zb='.cache.js',Ab='/',Gb='//',Tb='13E706BBD746E6C4EB0A4432BE5CA2B5',Ub='4D48F0FC3453C3A8ECE0FB91C0CE864B',Vb='5C759C2776B9A1CE1E11566C573105EE',Yb=':',pb='::',jc=':moduleBase',ab='<!doctype html>',cb='<html><head><\/head><body><\/body><\/html>',sb='=',zb='?',Wb='AF8A0EC389B1DB043CF3D70DFDD5E7F4',ub='Bad handler "',Xb='CE85E50117114444C92BF08B6D8B513D',_='CSS1Compat',fb='Chrome',eb='DOMContentLoaded',V='DUMMY',ic='Ignoring non-whitelisted Dev Mode URL: ',hc='__gwtDevModeHook:javascript',Fb='base',Db='baseUrl',Q='begin',W='body',P='bootstrap',Cb='clear.cache.gif',rb='content',ec='end',gb='eval("',gc='file:',Ob='gecko',Pb='gecko1_8',R='gwt.codesvr.javascript=',S='gwt.codesvr=',dc='gwt/clean/clean.css',wb='gwt:onLoadErrorFn',tb='gwt:onPropertyErrorFn',qb='gwt:property',lb='head',bc='href',fc='http:',Lb='ie10',Nb='ie8',Mb='ie9',X='iframe',Bb='img',T='javascript',Sb='javascript.devmode.js',Eb='javascript.nocache.js',Y='javascript:""',ob='javascript::',$b='link',cc='loadExternalRefs',mb='meta',kb='moduleRequested',jb='moduleStartup',Kb='msie',nb='name',Z='position:absolute; width:0; height:0; border:none; left: -1000px;',_b='rel',Jb='safari',ib='script',Rb='selectingPermutation',U='startup',ac='stylesheet',db='undefined',Qb='unknown',Hb='user.agent',Ib='webkit';var o=window;var p=document;r(P,Q);function q(){var a=o.location.search;return a.indexOf(R)!=-1||a.indexOf(S)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:T,sessionId:o.__gwtStatsSessionId,subSystem:U,evtGroup:a,millis:(new Date).getTime(),type:b})}}
javascript.__sendStats=r;javascript.__moduleName=T;javascript.__errFn=null;javascript.__moduleBase=V;javascript.__softPermutationId=0;javascript.__computePropValue=null;javascript.__getPropMap=null;javascript.__gwtInstallCode=function(){};javascript.__gwtStartLoadingFragment=function(){return null};var s=function(){return false};var t=function(){return null};__propertyErrorFunction=null;var u=o.__gwt_activeModules=o.__gwt_activeModules||{};u[T]={moduleName:T};var v;function w(){B();return v}
function A(){B();return v.getElementsByTagName(W)[0]}
function B(){if(v){return}var a=p.createElement(X);a.src=Y;a.id=T;a.style.cssText=Z+$;a.tabIndex=-1;p.body.appendChild(a);v=a.contentDocument;if(!v){v=a.contentWindow.document}v.open();var b=document.compatMode==_?ab:bb;v.write(b+cb);v.close()}
function C(k){function l(a){function b(){if(typeof p.readyState==db){return typeof p.body!=db&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(eb,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(eb,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=A();var f=w();var g;if(navigator.userAgent.indexOf(fb)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(gb));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode(hb));g=f.createElement(ib);g.language=T;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(ib);g.language=T;g.text=c[i];e.appendChild(g);d(e,g)}}}
javascript.onScriptDownloaded=function(a){l(function(){m(a)})};r(jb,kb);var n=p.createElement(ib);n.src=k;p.getElementsByTagName(lb)[0].appendChild(n)}
javascript.__startLoadingFragment=function(a){return G(a)};javascript.__installRunAsyncCode=function(a){var b=A();var c=w().createElement(ib);c.language=T;c.text=a;b.appendChild(c);b.removeChild(c)};function D(){var c={};var d;var e;var f=p.getElementsByTagName(mb);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(nb),k;if(j){j=j.replace(ob,bb);if(j.indexOf(pb)>=0){continue}if(j==qb){k=i.getAttribute(rb);if(k){var l,m=k.indexOf(sb);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=bb}c[j]=l}}else if(j==tb){k=i.getAttribute(rb);if(k){try{d=eval(k)}catch(a){alert(ub+k+vb)}}}else if(j==wb){k=i.getAttribute(rb);if(k){try{e=eval(k)}catch(a){alert(ub+k+xb)}}}}}t=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;javascript.__errFn=e}
function F(){function e(a){var b=a.lastIndexOf(yb);if(b==-1){b=a.length}var c=a.indexOf(zb);if(c==-1){c=a.length}var d=a.lastIndexOf(Ab,Math.min(c,b));return d>=0?a.substring(0,d+1):bb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(Bb);b.src=a+Cb;a=e(b.src)}return a}
function g(){var a=t(Db);if(a!=null){return a}return bb}
function h(){var a=p.getElementsByTagName(ib);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(Eb)!=-1){return e(a[b].src)}}return bb}
function i(){var a=p.getElementsByTagName(Fb);if(a.length>0){return a[a.length-1].href}return bb}
function j(){var a=p.location;return a.href==a.protocol+Gb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==bb){k=h()}if(k==bb){k=i()}if(k==bb&&j()){k=e(p.location.href)}k=f(k);return k}
function G(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return javascript.__moduleBase+a}
function H(){var f=[];var g;function h(a,b){var c=f;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
j[Hb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Ib)!=-1}())return Jb;if(function(){return b.indexOf(Kb)!=-1&&p.documentMode>=10}())return Lb;if(function(){return b.indexOf(Kb)!=-1&&p.documentMode>=9}())return Mb;if(function(){return b.indexOf(Kb)!=-1&&p.documentMode>=8}())return Nb;if(function(){return b.indexOf(Ob)!=-1}())return Pb;return Qb};i[Hb]={gecko1_8:0,ie10:1,ie8:2,ie9:3,safari:4};s=function(a,b){return b in i[a]};javascript.__getPropMap=function(){var a={};for(var b in i){if(i.hasOwnProperty(b)){a[b]=k(b)}}return a};javascript.__computePropValue=k;o.__gwt_activeModules[T].bindings=javascript.__getPropMap;r(P,Rb);if(q()){return G(Sb)}var l;try{h([Jb],Tb);h([Pb],Ub);h([Mb],Vb);h([Lb],Wb);h([Nb],Xb);l=f[k(Hb)];var m=l.indexOf(Yb);if(m!=-1){g=parseInt(l.substring(m+1),10);l=l.substring(0,m)}}catch(a){}javascript.__softPermutationId=g;return G(l+Zb)}
function I(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=p.createElement($b);b.setAttribute(_b,ac);b.setAttribute(bc,G(a));p.getElementsByTagName(lb)[0].appendChild(b);__gwt_stylesLoaded[a]=true}}
r(cc,Q);c(dc);r(cc,ec)}
D();javascript.__moduleBase=F();u[T].moduleBase=javascript.__moduleBase;var J=H();if(o){var K=!!(o.location.protocol==fc||o.location.protocol==gc);o.__gwt_activeModules[T].canRedirect=K;if(K){var L=hc;var M=o.sessionStorage[L];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(M)){if(M&&(window.console&&console.log)){console.log(ic+M)}M=bb}if(M&&!o[L]){o[L]=true;o[L+jc]=F();var N=p.createElement(ib);N.src=M;var O=p.getElementsByTagName(lb)[0];O.insertBefore(N,O.firstElementChild||O.children[0]);return false}}}I();r(P,ec);C(J);return true}
javascript.succeeded=javascript();